/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mouse;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dulce
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        setTitle("Menú ");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/7535422-Mouse-asustado-Looking-Up--Foto-de-archivo.jpg"));
        setIconImage(icon);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iniciar_Juego = new javax.swing.JButton();
        Instrucciones = new javax.swing.JButton();
        Niveles = new javax.swing.JButton();
        Historia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(688, 500));
        getContentPane().setLayout(null);

        Iniciar_Juego.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        Iniciar_Juego.setText("Iniciar Juego");
        Iniciar_Juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_JuegoActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar_Juego);
        Iniciar_Juego.setBounds(90, 60, 120, 27);

        Instrucciones.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        Instrucciones.setText("Ver Instrucciones");
        Instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(Instrucciones);
        Instrucciones.setBounds(510, 130, 170, 30);

        Niveles.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        Niveles.setText("Escoger Escenario");
        Niveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelesActionPerformed(evt);
            }
        });
        getContentPane().add(Niveles);
        Niveles.setBounds(80, 130, 160, 30);

        Historia.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        Historia.setText("Ver Historia");
        Historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(Historia);
        Historia.setBounds(530, 50, 120, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoriaActionPerformed

        {
        try {
            Desktop.getDesktop().browse(new URI("http://mazequest.bravesites.com"));
        } catch (URISyntaxException | IOException e) {
        }
    }

    }//GEN-LAST:event_HistoriaActionPerformed

    private void Iniciar_JuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_JuegoActionPerformed

  this.dispose();
  Nivel1 j = new Nivel1();
  j.setBounds(30,30,600,520);
  j.setLocationRelativeTo(null);
  j.setVisible(true);
 JOptionPane.showMessageDialog(null,"Para salir haga clic primero en comenzar y \n"
         + "después presiona la tecla X");
  
// TODO add your handling code here:
    }//GEN-LAST:event_Iniciar_JuegoActionPerformed

    private void NivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelesActionPerformed
        this.dispose();
        Niveles a= new Niveles();
        a.setBounds(30,30,700,520);//setBounds(10, 10, 600,500);
        a.setLocationRelativeTo(null);
        a.setVisible(true);
       
// TODO add your handling code here:
    }//GEN-LAST:event_NivelesActionPerformed

    private void InstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstruccionesActionPerformed
  
        JOptionPane.showMessageDialog(this, "INSTRUCCIONES \n"
                + "1.- El boton INICIAR permite comenzar el juego desde 0.\n"
                + "2.- Tu objetivo es salir del laberinto.\n"
                + "3.- Cada que salgas podrás cambiar de Nivel\n"
                + "4.- Igual puedes escoger los escenarios si te sientes un \n"
                + "un experto.\n"
                + "5.-Cada que topes con una trampa tendrás que \n"
                + " resolver un problema.\n"                
                + "6.-8.- Si no puedes resolver la pregunta da Clic en Cancelar \n"
                + "y busca otra salida antes de que pierdas tus vidas\n"
                + "al contestar mal." );      
  
        

// TODO add your handling code here:
    }//GEN-LAST:event_InstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historia;
    private javax.swing.JButton Iniciar_Juego;
    private javax.swing.JButton Instrucciones;
    private javax.swing.JButton Niveles;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
