/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mouse;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Dulce
 */
public class Niveles extends javax.swing.JFrame {

    /**
     * Creates new form Niveles
     */
    public Niveles() {
        setTitle("Niveles");
        initComponents();
               
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/7535422-Mouse-asustado-Looking-Up--Foto-de-archivo.jpg"));
        setIconImage(icon);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sala = new javax.swing.JButton();
        baño = new javax.swing.JButton();
        cuarto = new javax.swing.JButton();
        cocina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TEXTO = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sala.png"))); // NOI18N
        sala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaActionPerformed(evt);
            }
        });
        getContentPane().add(sala);
        sala.setBounds(20, 10, 230, 210);

        baño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bañp.jpg"))); // NOI18N
        baño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bañoActionPerformed(evt);
            }
        });
        getContentPane().add(baño);
        baño.setBounds(270, 10, 230, 210);

        cuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuarto.png"))); // NOI18N
        cuarto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartoActionPerformed(evt);
            }
        });
        getContentPane().add(cuarto);
        cuarto.setBounds(20, 240, 230, 210);

        cocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cocina.png"))); // NOI18N
        cocina.setText("jButton1");
        cocina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinaActionPerformed(evt);
            }
        });
        getContentPane().add(cocina);
        cocina.setBounds(270, 240, 230, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rata.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 250, 130, 230);

        TEXTO.setBackground(new java.awt.Color(51, 51, 255));
        TEXTO.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        TEXTO.setText("ELIGE UN ESCENARIO");
        getContentPane().add(TEXTO);
        TEXTO.setBounds(460, 170, 220, 120);

        btn_menu.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        btn_menu.setText("Menú");
        btn_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu);
        btn_menu.setBounds(510, 50, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/332929.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaActionPerformed
  this.dispose();
  Nivel1 j = new Nivel1();
  j.setBounds(30,30,600,520);
  j.setLocationRelativeTo(null);
  j.setVisible(true);
   JOptionPane.showMessageDialog(null,"Para salir haga clic primero en comenzar \n"
           + "y después presiona la tecla X");
  
        
// TODO add your handling code here:
    }//GEN-LAST:event_salaActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
  this.dispose();
  Inicio j = new Inicio();
  j.setBounds(30,30,700,480);
  j.setLocationRelativeTo(null);
  j.setVisible(true);
 
        // TODO add your handling code here:
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_menuActionPerformed

    private void bañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bañoActionPerformed
 this.dispose();
  Nivel2 a = new Nivel2();  
  a.setBounds(30,30,600,520);
  a.setLocationRelativeTo(null);
  a.setVisible(true);
  JOptionPane.showMessageDialog(null,"Para salir haga clic primero en comenzar y\n"
          + " después presiona la tecla X");


// TODO add your handling code here:
    }//GEN-LAST:event_bañoActionPerformed

    private void cuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartoActionPerformed
  this.dispose();
  Nivel3 a = new Nivel3();  
  a.setBounds(30,30,600,520);
  a.setLocationRelativeTo(null);
  a.setVisible(true);
   JOptionPane.showMessageDialog(null,"Para salir haga clic primero en comenzar \n"
           + "y después presiona la tecla X");
  

        

// TODO add your handling code here:
    }//GEN-LAST:event_cuartoActionPerformed

    private void cocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinaActionPerformed
  this.dispose();
  Nivel4 a = new Nivel4();  
  a.setBounds(30,30,600,520);
  a.setLocationRelativeTo(null);
  a.setVisible(true);
  //JOptionPane.showMessageDialog(null,"Para salir haga clic primero en comenzar y\n"
   //       + " después presiona la tecla X");


        
// TODO add your handling code here:
    }//GEN-LAST:event_cocinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Niveles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TEXTO;
    private javax.swing.JButton baño;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton cocina;
    private javax.swing.JButton cuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sala;
    // End of variables declaration//GEN-END:variables
}
